import './css/style.css'

import { Inter, Poppins } from 'next/font/google'
import { CSPostHogProvider } from './providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <CSPostHogProvider>
      <body className={`${inter.variable} ${poppins.variable} font-poppins antialiased bg-cyan-1 text-slate-100 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </CSPostHogProvider>
    </html>
  )
}
