import './css/style.css'

import { Inter, Poppins } from 'next/font/google'
import {  Suspense } from 'react';
import { PHProvider, PostHogPageview } from './providers';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en"  className='dark'>
    <Suspense>
      <PostHogPageview />
    </Suspense>
    <PHProvider>
      <body className={`${inter.variable} ${poppins.variable} font-poppins antialiased bg-[#0F1729] text-slate-100 tracking-tight`}>

        <div className="flex flex-col min-h-screen overflow-hidden">
          {children}
        </div>

      </body>
    </PHProvider>

    </html>

  )
}
